### ISSUE TITLE
Potential bug in the plugin in Obsidian v. 1.5.5

### ISSUE THREAD

**Issue by TomBirkland** [beaussan/update-time-on-edit-obsidian#70] opened 2024-02-14 04:28 UTC
Under the editor v 1.5.5, this plugin appears to misbehave. Instead of including the file date and file modified date in the YAML front matter, the plugin appears to insert these dates in a loop that recurrs about thirty times, yielding results like this.

> created: 2024-02-13T22:25
> updated: 2024-02-13T22:25
> created: 2024-02-13T22:25
> updated: 2024-02-13T22:25
> created: 2024-02-13T22:25
> updated: 2024-02-13T22:25

Disabling the plugin stops the error, but removes its functionality. Reinstalling the plugin replicates the error. It seems that the plugin isn't forming YAML correctly. Sorry if this is insufficiently detailed--I am not a programmer, but am an end user.

**Comment by optimikelabs** [comment] 2024-02-14 10:32
Same bug for me

**Comment by elvarb** [comment] 2024-02-14 11:24
This seems to happen only if there is no frontmatter defined in the file.

**Comment by TomBirkland** [comment] 2024-02-14 14:02
> This seems to happen only if there is no frontmatter defined in the file.

This is exactly what I found. So a workaround would be to make sure that there's some frontmatter defined. I think I might be able to use the Templater plugin to fix this. But this wasn't required before this bug arose, so it would be good to see a solution.

**Comment by mikemp7** [comment] 2024-02-15 15:28
+1. Workaround works. But aggro bug ...

**Comment by spiritualgeek** [comment] 2024-02-16 12:06
> Under the editor v 1.5.5, this plugin appears to misbehave. Instead of including the file date and file modified date in the YAML front matter, the plugin appears to insert these dates in a loop that recurrs about thirty times, yielding results like this.
> 
> > created: 2024-02-13T22:25
> > updated: 2024-02-13T22:25
> > created: 2024-02-13T22:25
> > updated: 2024-02-13T22:25
> > created: 2024-02-13T22:25
> > updated: 2024-02-13T22:25
> 
> Disabling the plugin stops the error, but removes its functionality. Reinstalling the plugin replicates the error. It seems that the plugin isn't forming YAML correctly. Sorry if this is insufficiently detailed--I am not a programmer, but am an end user.

Exactly the same for me and I can't live without this plugin :(

**Comment by gapmiss** [comment] 2024-02-16 13:51
If this is the cause of the issues, it will be fixed in next update.

https://forum.obsidian.md/t/automatically-update-last-modified-date-in-note/51776/64

**Comment by beaussan** [comment] 2024-02-16 14:30
Hey everyone, turns out it was an obsidian bug! 

I was trying many thing to circle around it to ensure this was not happening, trying double updates, going back to editing manually the front matter, but since they are fixing it in next update, this should be good!

For you information, now this plugin [relies heavily](https://github.com/beaussan/update-time-on-edit-obsidian/blob/main/src/main.ts#L176) on `app.fileManager.processFrontMatter` from obsidian directly so that I have the same read and write system that obsidian itself uses to ensure the implementation doesn't drift from the official one.

Keeping this thread open until they fixed it, in the meantime, I suggest to go back to a stable obsidian version where this bug is not present

**Comment by TomBirkland** [comment] 2024-02-16 15:02
> Hey everyone, turns out it was an obsidian bug!
> 
I thought this might be the case. I don't rely on this as heavily as other folks, so I am using Linter as a stopgap now but will reinstall this plugin (it's incredibly useful) when Obsidian updates the editor. Thanks for the quick followup.

**Comment by gapmiss** [comment] 2024-02-17 11:30
This is now fixed in beta v1.5.6 (Insider's release)

**Comment by TomBirkland** [comment] 2024-02-17 22:39
> This is now fixed in beta v1.5.6 (Insider's release)

Thanks for letting us know! I confirmed that it works as before.

**Comment by FeralFlora** [comment] 2024-02-29 17:32
The fix should be public now, so this can be closed?

**Closed as completed** 2024-02-29 19:36 UTC
Labels: bug, External dependancy, Has workaround
