### ISSUE TITLE
Creation date gets changed.

### ISSUE THREAD

**Issue by Inclement9** [beaussan/update-time-on-edit-obsidian#41] opened 2023-01-06 12:41 UTC
Compare the file creation dates on these two screenshots. The created date should be the same on both.

Windows file properties box for this file:
<img width="273" alt="image" src="https://user-images.githubusercontent.com/61940529/211174516-1b57281c-3d5d-4fac-892a-7bcbf75696e6.png">

Obsidian metadata:
<img width="240" alt="image" src="https://user-images.githubusercontent.com/61940529/211174444-bc024e7b-0b47-4af5-9dfd-51cc388edb17.png">

**Comment by profucius** [comment] 2023-01-07 15:27
@beaussan 
This is happening to me too. This is a MAJOR bug. It changes the create date every time it changes the updated time, and it seems to be changing the date to the past. One file example, which was created this year, had its created date changed to 2022-05-02, and then another time it was changed to 2022-05-04. This file was _certainly_ not created that long ago. Screenshot below.

I am going to disable this plugin until the issue is resolved. It has terribly destroyed the validity of all my file dates, which will be a massive headache to find a solution for, if I even can.

![majorbug](https://user-images.githubusercontent.com/18254607/211158222-328dd067-edbc-49f7-8f74-348d5510079b.png)

**Comment by Inclement9** [comment] 2023-01-07 15:46
In [this issue post](https://github.com/beaussan/update-time-on-edit-obsidian/issues/33), Mrienstra quotes a suggestion from another message that people use the Linter plugin instead.

I've done that - uninstalled this one, installed Linter - and Linter seems to be adding the dates perfectly, as best I can tell in 24 hours.

If you're not already familiar with Linter (I wasn't), it's a much bigger plugin with many, many features. Make sure to go through and double-check that anything you don't want is turned off. Most things seem to be off by default - opt-in, not opt-out - but it can change your files so it's worth checking.

If Linter doesn't generate the created/modified frontmatter automatically, you can trigger it manually by "saving" with Ctrl-S. That works. (I'm too new to it to understand the whys and wherefores.)

**Comment by Inclement9** [comment] 2023-01-07 15:51
Oh - @profucius - in Settings > Core Plugins, do you have File Recovery turned on? That _might_ help you. (I'm not very familiar with it, either.)

**Comment by profucius** [comment] 2023-01-07 16:02
Wellll, I did have File Recovery turned on at one point, but disabled it due to using Syncthing to sync my vault to my android obsidian app. It comes with its own versioning, so I was relying on it instead, but then I just noticed that this bug caused Syncthing to go haywire and create hundreds of sync-conflict versions, all with either the same content and only the frontmatter dates changed, or sometimes with the content also changed (due to editing the file on my phone). Its a file-versioning nightmare that unfortunately I don't have the time to untangle. The good news at the very least is that I don't edit on my phone very much, so I will just fall back to a previous vault backup, and restore a few files.

Linter looks interesting, thanks for mentioning that! I'll be giving it a try after I get my vault stable again (and another backup!)

Let this thread be a cautionary tale to any who may come across this. Unfortunately without the author updating the Readme.md landing page, some more people will probably fall victim to the bug until then.

**Comment by profucius** [comment] 2023-01-07 23:32
> In [this issue post](https://github.com/beaussan/update-time-on-edit-obsidian/issues/33), Mrienstra quotes a suggestion from another message that people use the Linter plugin instead.
> 
> I've done that - uninstalled this one, installed Linter - and Linter seems to be adding the dates perfectly, as best I can tell in 24 hours.
> 
> If you're not already familiar with Linter (I wasn't), it's a much bigger plugin with many, many features. Make sure to go through and double-check that anything you don't want is turned off. Most things seem to be off by default - opt-in, not opt-out - but it can change your files so it's worth checking.
> 
> If Linter doesn't generate the created/modified frontmatter automatically, you can trigger it manually by "saving" with Ctrl-S. That works. (I'm too new to it to understand the whys and wherefores.)

I tested Linter and it worked perfectly. I only enabled the dates section settings. FYI, you can actually make it write to all files. If you're comfortable with the settings and you've tested it on some select files, then you can open the command palette and type Linter and there is an option to lint all files in vault. I went ahead and did that (after a backup) and everything I've looked at is perfect so far. Thanks again for bringing that to my attention, you saved my toosh there.

**Comment by beaussan** [comment] 2023-07-27 19:00
Hi, sorry for the delay. This should now be fixed as of 2.0.0. If that's still an issue, feel free to re open a new issue !

**Closed by beaussan** 2023-07-27 19:00 UTC
