### ISSUE TITLE
Feature request: Replace the `T` with a space ` `

### ISSUE THREAD

**Issue by huyz** [beaussan/update-time-on-edit-obsidian#2] opened 2021-10-05 11:39 UTC
I think that replacing the `T` with a space ` ` is still valid RFC3339 https://datatracker.ietf.org/doc/html/rfc3339#section-5.6

So could you remove the `T` to make the output cleaner and more readable?

Thanks

**Comment by huyz** [comment] 2021-10-05 23:13
Maybe you could do a simple string replace on the output of the library function?

**Comment by beaussan** [comment] 2021-10-10 09:07
Duplicate of #3

**Closed by beaussan** 2021-10-10 09:07 UTC
