### ISSUE TITLE
Ruins the whole frontmatter if it has strings that have colons ":" in them

### ISSUE THREAD

**Issue by guideblade** [beaussan/update-time-on-edit-obsidian#54] opened 2023-08-06 15:39 UTC
Upon the update it ruins YAML keys that are strings that contain colons.
`title: "Avatar: The Last Airbender"` becomes `title: "Avatar`. And, of course, it throws YAML exception since there is no quotation marks at the end. Ruins the whole YAML.
Also the new version 2.0.2 is crazy. It updates the value each millisecond. Had to revert.

**Comment by beaussan** [comment] 2023-08-06 15:55
> Upon the update it ruins YAML keys that are strings that contain colons.
title: "Avatar: The Last Airbender" becomes title: "Avatar. And, of course, it throws YAML exception since there is no quotation marks at the end. Ruins the whole YAML.

What version of the plugin are you running? I can't reproduce it in 2.x

> Also the new version 2.0.2 is crazy. It updates the value each millisecond.
Currently looking into it to improve the system

**Comment by beaussan** [comment] 2023-08-06 21:44
> Also the new version 2.0.2 is crazy. It updates the value each millisecond.

Fixed in 2.1.0.

**Closed by beaussan** 2023-08-06 21:44 UTC

**Comment by guideblade** [comment] 2023-08-16 14:43
> > Upon the update it ruins YAML keys that are strings that contain colons.
> > title: "Avatar: The Last Airbender" becomes title: "Avatar. And, of course, it throws YAML exception since there is no quotation marks at the end. Ruins the whole YAML.
> 
> What version of the plugin are you running? I can't reproduce it in 2.x
> 
> > Also the new version 2.0.2 is crazy. It updates the value each millisecond.
> 
> Currently looking into it to improve the system

I updated to 2.2.0, it still does it. But now it also makes other unsolicited changes to the frontmatter like making empty keys contain "null", or changing all indentation to two spaces (I use one). Also, now when I add a new key, it updates the note, my cursor gets taken to the update key, which becomes peupdate key (because I was typing "type" - it didn't let me finish), and it creates a new update key down below.
Reverted back to 1.1.2 again, imho the best version, bug free.
