### ISSUE TITLE
I can' t use the templater function "Folder template"  if I use this plugin

### ISSUE THREAD

**Issue by lisasuosuo** [beaussan/update-time-on-edit-obsidian#50] opened 2023-07-28 05:03 UTC
If I use templater to create a new file in a folder , this plugin will add the YAML "update",so my  template can't use.I think may be it has conflict with it.

**Comment by beaussan** [comment] 2023-07-28 08:35
This should be fixed with the 2.0.1 version :tada:
Feel free to reopen an issue if this is still an issue

**Closed by beaussan** 2023-07-28 08:35 UTC
Labels: bug

**Comment by lisasuosuo** [comment] 2023-08-03 02:29
It works！ Thanks for your great work!

**Comment by danielo515** [comment] 2023-08-09 15:11
I have the 2.0.1 version, but I still get some weird things. For example, inserting a template the plugin gets triggered and I run into similar problems

**Comment by beaussan** [comment] 2023-08-09 15:41
@danielo515 can you try updating to the latest version? And if that is still an issue, feel free to create a new issue with a reproduction. I use templater heavily and I don't have issues around using it with this plugin currently

**Comment by danielo515** [comment] 2023-08-09 15:51
sorry, what is the latest version? is not yet published?

**Comment by danielo515** [comment] 2023-08-10 09:51
Here is an example template for newly created note that conflicts with this plugin. By the time my template completes, this plugin has inserted a first front-matter:

```
<%*
  let title = tp.file.title
  if (title.startsWith("Untitled")) {
    title = await tp.system.prompt("Title");
    await tp.file.rename(title);
  } 
  const tags = ['type/']
_%>
---
tags: <% tags %>
aliases: 
title:  <%* tR += title %>
created: <% tp.date.now() %>
---

<%tp.file.cursor(1)%>
```

**Comment by elvarb** [comment] 2023-08-31 10:34
Same issue here, happens most of the time with my templates. I think this is because this plugin triggers as soon as the page is created and we have issues as templates can be applied in many ways/steps when creating a page that uses a template.

Issues when...

- Creating a page from the Kanban plugin where it automatically sets the template
- When using Quickadd to trigger a page creation with a template

No issues when...

- Creating a page directly in a folder where Templater has a rule to use a template
